### ISSUE TITLE
Linking between pages

### ISSUE THREAD

**Issue by tachyondecay** [symphonycms/docs.getsymphony.com#16]
What is the best way to do this?

I tried using `{% post_url %}` at first, until I realize that only applies to posts, not pages….

Right now I’m just hard-coding the link, but that presents issues with the base URL: I have to hardcode `/docs.symphony.com/` into the links for now, only to remove it when we change to a subdomain, or the links don’t work.

**Comment by johnpuddephatt** [comment]
Using `{% site.baseurl %}` should work – based on the current setup it returns `docs.getsymphony.com`.

**Comment by tachyondecay** [comment]
Great minds think alike! I just tried that after consulting the Jekyll docs, and it does indeed work.

**Comment by bernardodiasc** [comment]
`{% site.baseurl %}` will return `/docs.getsymphony.com` (with the slash) :)
