### ISSUE TITLE
Default branch should be gh-pages

### ISSUE THREAD

**Issue by bernardodiasc** [symphonycms/docs.getsymphony.com#2]
@brendo, I don't have permission to change settings, can you please make this change?
Thanks!

**Comment by nilshoerrmann** [comment]
What would you like to have changed in the settings?

**Comment by brendo** [comment]
Done.

**Comment by bernardodiasc** [comment]
@nilshoerrmann we'll have only gh-pages in this repo.

Thanks @brendo!
