### ISSUE TITLE
Adapt Factory UI

### ISSUE THREAD

**Issue by bernardodiasc** [symphonycms/docs.getsymphony.com#6]
Currently, the Factory layout have some informations that we'll not need or can't have in this Jekyll setup. Like user, regions, etc. Factory is pretty neat, probably not much will be changed.

![screenshot-symphonycms github io 2015-01-23 12-36-33](https://cloud.githubusercontent.com/assets/131859/5876252/f78f4490-a2fc-11e4-8b5c-84d8475526ac.png)

/cc @nilshoerrmann suggestions are welcome :)

**Comment by nilshoerrmann** [comment]
The layout of the Factory repository is just an example. Please change the content structure to whatever seems to be appropriate today.

The last thing we did when working on Factory was to ask administrators of existing community site which layout modules they needed for their specific content. We never got feedback due to the changes in the working group staff (a lot of members were switching jobs or just moved away from Symphony at that time).

Things I remember to be still a bit crude:
- huge lists in the sidebar (e. g. for content indexes)
- navigation between sections on the same page (something like smooth scrolling)
- headline hierachy

There are certainly things that need to be added in the CSS to make everything look good in the docs. If you've worked a bit with Factory, we can have a chat or hangout if you like to discuss the state of things.

**Comment by nilshoerrmann** [comment]
Ah and just a tip: Start working on the documentation and use Factory as it is. Take notes on what works and what doesn't. Adjust Factory to your needs after the docs have taken form (@johannahoerrmann and I can assists you, if you like).

**Comment by bernardodiasc** [comment]
> Ah and just a tip: Start working on the documentation and use Factory as it is.

Cool, that's the plan. Content is the king!

For the moment I'm thinking in just hide some elements on the page, don't want to invest time in frontend coding before have a good content structure with the content in it. Lets keep the notes for future bigger adjustments in this loop.

**Comment by johnpuddephatt** [comment]
Thanks for the offer of help @nilshoerrmann :) 

@bernardodiasc – perhaps just hide all of aside#network for now?

**Comment by bernardodiasc** [comment]
As mentioned, dont want to invest time in this, but I had to polish a little bit the header to fit our needs. I'll miss the popup panel, but for now we dont need it. What ya think?

![screenshot-127 0 0 1 4000 2015-01-23 17-17-07](https://cloud.githubusercontent.com/assets/131859/5880964/c4dacf8e-a323-11e4-88bf-23e91f673fa5.png)

**Comment by nitriques** [comment]
LGTM !! :rocket:

**Comment by johnpuddephatt** [comment]
Poor [xpathr](http://xpathr.com)!

**Comment by bernardodiasc** [comment]
Hmm, not sure if this one is working, last time I tried didn't.

The [Ninjas](http://symphonyninjas.com/) is nice, but also not sure if its up to date.

We can include both anytime though.

**Comment by johnpuddephatt** [comment]
Haha, I was only joking about xPathr (although it should be working... I think!). It doesn't matter too much anyway as this is just for while things are being worked on – as @nilshoerrmann has said we should look at tailoring Factory at the end when the content is done.

I think an obvious next step in terms of Factory integration is going to be getting the primary navigation to work.

Even though it may take a little time for the content of said navigation to be decided, a functioning primary navigation with section pages that load the relevant secondary (or sub-) navigation is a good thing to be working towards.

**Comment by bernardodiasc** [comment]
indeed, our priority now goes to #8. I'm reading the references, but is quite a lot, taking some time.

**Comment by bernardodiasc** [comment]
Alright, it's adapted already. Closing this for now. We'll find the need to think the itens Nils mentioned eventually, for sure, they are intrinsically related to the content structure and the content itself.

> - huge lists in the sidebar (e. g. for content indexes)
> - navigation between sections on the same page (something like smooth scrolling)
> - headline hierachy

**Comment by johnpuddephatt** [comment]
Given that Factory is intended to provide a consistent experience across all Symphony sites, I think it would make sense for the factory.css file to be left untouched while the documentation site is being developed.

I realise only minor amends have been made at the moment (e.g. for the search input field), but I think there's a danger that making amends to this file directly makes things more complicated in the long run. Instead, any additions should perhaps be made in a separate file.

@nilshoerrmann – do you have any thoughts on the best approach here? You've already suggested that styling changes are left to the end, but I also realise there are some instances where it's desirable to style things in a reasonable way in the short term to confirm their viability. I imagine that keeping such styling to a separate css file would be best?

**Comment by nilshoerrmann** [comment]
The original idea was to have a unified Factory stylesheet and additional files for the different network site (adding or overriding definitions). This way, new design pattern can be tested easily on a per site basis and can be merged with the Factory core as soon as they are stable (only in case they seem to be helpful for the majority of the network of course).

**Comment by bernardodiasc** [comment]
Indeed, this makes a lot sense. I'll cleanup the changes I did and use it in another file.

**Comment by johnpuddephatt** [comment]
Sounds good!
