### ISSUE TITLE
Agree a content structure

### ISSUE THREAD

**Issue by bernardodiasc** [symphonycms/docs.getsymphony.com#7]
As suggested by @johnpuddephatt:

> Initially it makes sense to gather all available resources in one place. These resources collectively act as valuable source material for the docs. In order that the finished product meets the needs of Symphony users, however, we can't let ourselves be limited by what source material already exists – there may (/will) be gaps that need filling!
> 
> We should therefore agree a content structure that we can work towards. 
> 
> Added benefits of this will be: 1) it makes it easier for others to contribute (as they can see what needs to be done), and 2) it will provide a useful way of tracking progress as pages/sections are completed and ticked off.
> 
> Usefully, some content structures have already been proposed, both in the [Google Drive Factory notes](https://drive.google.com/folderview?id=0B26ZhsIIFPEmcDBmdjYwb2dyblk&usp=sharing&tid=0B26ZhsIIFPEmWXI4Qi1pdHlSbjA), and [here on Github](https://github.com/symphonycms/docs/wiki/Content-Structure-Proposal).
> 
> At first glance these seem quite reasonable and don't conflict with one another too much. It might be useful to get a bit of wider input here to see if there are any glaring omissions.

**Comment by johnpuddephatt** [comment]
I'm going to post a new issue that's a bit more fleshed out than the above.
