### ISSUE TITLE
Search input feature

### ISSUE THREAD

**Issue by bernardodiasc** [symphonycms/docs.getsymphony.com#9]
As suggested in #8, a search input would be a very nice feature to have.

**Comment by bernardodiasc** [comment]
@johnpuddephatt the search input works!

https://symphonycms.github.io/docs.getsymphony.com/

used this reference http://thornelabs.net/2014/05/12/instant-search-with-twitter-bootstrap-jekyll-json-and-jquery.html

its just a draft still, filtering only titles. :)

**Comment by bernardodiasc** [comment]
Ready. I've replaced the main navigation for a while. Until we have enough content to fill that much places for navigation will be ok like this.

![screenshot-symphonycms github io 2015-01-25 02-27-52](https://cloud.githubusercontent.com/assets/131859/5890255/c9c6e3a4-a439-11e4-8eea-6eac04295da1.png)

Closing this issue, anyway, suggestions are welcome.

**Comment by johnpuddephatt** [comment]
Awesome! 

In search.js on line 52, it might be worth changing:

`if ($input.val() != '') {`
to
`if ($input.val().trim().length > 2) {`

This will stop the search from triggering until at least three characters have been entered. There's little point showing a list of results when a single character has been entered...

**Comment by johnpuddephatt** [comment]
I've just made the previously mentioned change so that it can be reviewed/tested

**Comment by bernardodiasc** [comment]
Nice, thanks!

If we need that space again for main menu, this search box can be moved to the left-side column. Or somewhere else. Design thinking is definitely not my strong point. :)

**Comment by johnpuddephatt** [comment]
Sounds good!

**Comment by nitriques** [comment]
+1 :shipit:
